{{- if not .Values.registry.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.registry.secretName }}
data:
  .dockerconfigjson: {{ .Values.registry.secret }}
type: kubernetes.io/dockerconfigjson
{{- end }}



